import { SquickyPlayer } from "../core/SquickyPlayer";
import type { SquickySource, SquickyTextTrack } from "../core/types";
export declare class SquickyPlayerElement extends HTMLElement {
    static readonly observedAttributes: string[];
    private root;
    private core;
    private hideTimer;
    private settingsOpen;
    private preferredTextTrack;
    private lastTapAt;
    private objectUrls;
    private resumeResolver;
    private chaptersRenderKey;
    private previewRequest;
    private previewImages;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    attributeChangedCallback(): void;
    get player(): SquickyPlayer | null;
    load(source: SquickySource): Promise<void>;
    loadFile(file: File): Promise<void>;
    loadSubtitleFile(file: File, options?: Partial<Pick<SquickyTextTrack, "id" | "label" | "srclang" | "kind" | "default">>): Promise<SquickyTextTrack>;
    private template;
    private bindUi;
    private bindCore;
    private render;
    private renderTimeline;
    private renderVolume;
    private renderQualities;
    private renderAudioTracks;
    private renderSelectedAudioTrack;
    private renderRemotePlayback;
    private renderTextTracks;
    private renderSelectedTextTrack;
    private renderChapters;
    private renderActiveChapter;
    private renderError;
    private errorTitle;
    private errorMessage;
    private handleKeyboard;
    private handleStageTap;
    private seekWithFeedback;
    private updatePreview;
    private updatePreviewAtRatio;
    private hidePreview;
    private renderPreviewImage;
    private clearPreviewImage;
    private toggleSettings;
    private toggleCaptions;
    private requestResume;
    private resolveResume;
    private showControls;
    private scheduleControls;
    private syncCapabilities;
    private loadAttributes;
    private query;
}
export declare function defineSquickyPlayer(tagName?: string): void;
//# sourceMappingURL=SquickyPlayerElement.d.ts.map