import type { PlayerEventHandler, PlayerEventName, PlayerSnapshot, SquickyPlayerApi, SquickyPlayerOptions, SquickySource, SquickyTextTrack } from "./types";
export declare class SquickyPlayer implements SquickyPlayerApi {
    readonly media: HTMLMediaElement;
    readonly capabilities: import("./types").PlayerCapabilities;
    private readonly events;
    private readonly sources;
    private readonly plugins;
    private destroyed;
    private source;
    private streamKind;
    private status;
    private qualities;
    private selectedQuality;
    private audioTracks;
    private selectedAudioTrack;
    private selectedTextTrack;
    private chapters;
    private activeChapterId;
    private thumbnails;
    private thumbnailLoadToken;
    private remotePlaybackAvailable;
    private remoteAvailabilityWatchId;
    constructor(options: SquickyPlayerOptions);
    get snapshot(): PlayerSnapshot;
    load(source: SquickySource): Promise<void>;
    play(): Promise<void>;
    pause(): void;
    toggle(): Promise<void>;
    seek(time: number): void;
    seekBy(seconds: number): void;
    setVolume(volume: number): void;
    setMuted(muted: boolean): void;
    setPlaybackRate(rate: number): void;
    setQuality(id: string): void;
    setAudioTrack(id: string): void;
    addTextTrack(trackSource: SquickyTextTrack): void;
    setTextTrack(id: string): void;
    seekToChapter(id: string): void;
    previousChapter(): void;
    nextChapter(): void;
    requestFullscreen(): Promise<void>;
    requestPictureInPicture(): Promise<void>;
    requestRemotePlayback(): Promise<void>;
    requestAirPlay(): void;
    on<K extends PlayerEventName>(event: K, handler: PlayerEventHandler<K>): () => void;
    destroy(): Promise<void>;
    private readonly mediaHandlers;
    private bindMediaEvents;
    private unbindMediaEvents;
    private setupPlugins;
    private loadThumbnails;
    private replaceTextTracks;
    private appendTextTrack;
    private readonly handleTextTracksChange;
    private syncTextTracks;
    private getTextTracks;
    private toTextTrackInfo;
    private textTrackId;
    private textTrackIndex;
    private isCaptionTrack;
    private createTextTrackId;
    private findTextTrackId;
    private getActiveChapter;
    private updateActiveChapter;
    private bindRemotePlayback;
    private unbindRemotePlayback;
    private readonly handleRemotePlaybackChange;
    private getRemotePlaybackState;
    private handleNativeError;
    private reportError;
    private emitState;
    private assertActive;
}
//# sourceMappingURL=SquickyPlayer.d.ts.map